<?php

namespace Tests\Feature\LMS\Lesson\Http\Controllers;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use LMS\Modules\Models\Module;
use LMS\User\Models\User;
use Tests\TestCase;

class LessonsControllerTest extends TestCase
{
    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }

    public function testUserCanCreateALesson()
    {
        // Prepare
        $module = Module::factory()->create();

        $payload = [
            'type_id' => 1,
            'title' => 'dasdsadasdasdsa',
            'description' => 'dasdsadsa'
        ];
        // Act
        $this->actingAs($module->course->author);
        $response = $this->post(
            route('instructor-course-lesson-new', ['course' => $module->course, 'module' => $module]),
            $payload
        );
        $response->dump();

        // Assert
        $response->assertOk();
    }

    public function testUserShouldNotCreateALessonInACourseThatDoesNotBelongsToHim()
    {
        // Prepare
        $module1 = Module::factory()->create();
        $module2 = Module::factory()->create();

        $payload = [
            'type_id' => 1,
            'title' => 'dasdsadasdasdsa',
            'description' => 'dasdsadsa'
        ];
        // Act
        $this->actingAs($module1->course->author);
        $response = $this->post(
            route('instructor-course-lesson-new', ['course' => $module1->course, 'module' => $module2]),
            $payload
        );
        $response->dump();

        // Assert
        $response->assertStatus(422);
    }
}
